project:
  type: book

book:
  title: "Introduction to Data Science"
  subtitle: "STAT 3255/5255 @ UConn, Fall 2025"
  author:
    - name: "[Jun Yan](https://statcomp.org) and Students in Fall 2025"
    - name: Matthew Anzalone
    - name: Irene Chen
    - name: Jingang Chen
    - name: Enshuo Cao
    - name: Alejandro Haerter
    - name: Hannah Levine
    - name: Sonia Lucey
    - name: Jaden Mayer-Costa
    - name: Lewis Milun
    - name: Sahil Patel
    - name: Jack Perkins
    - name: Alexander Plotnikov
    - name: Quinn Saltus
    - name: Jacob Schlessel
    - name: Owen Sgro
    - name: Wilson Tang
    - name: Justin Tran
    - name: Abigail White
    - name: Jessica Yoon
    - name: Mark Zhang
  date: today

#  sidebar:
#    logo: images/ids-f24.png
  
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-git.qmd
    - 03-quarto.qmd
    - 04-python.qmd
    - 05-visualization.qmd
    - 06-manipulation.qmd
    - 07-exploration.qmd
    - 08-regression.qmd
    - 09-classification.qmd
    - 10-supervised.qmd
    - 11-unsupervised.qmd
    - 90-advanced.qmd
    - 95-exercises.qmd
    - 99-references.qmd

bibliography:
    - references.bib
    - jyrefs.bib

csl: apa.csl

format:
  html:
    html-math-method: mathjax
    theme: cosmo
#  pdf:
#    documentclass: scrbook
#    include-in-header: preamble.tex
#    prefer-html: true

execute:
  freeze: auto